version: "3"
services:
  web:
    container_name: gatsby-dev-luc
    build:
      context: . 
      dockerfile: ./Dockerfile.development
    ports:
      - "8006:8006"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules