---
title: "Dockerfile"
description: "Reference for Dockerfile management"
date-created: '2023/02/20'
last-modified: '2023/03/03'
categories: ["docker", "development", "dockerfile"]
tags: ["docker", "development", "dockerfile", "notes"]
isdraft: true
type: "note"
---

## DockerFile Reference

### ENV

[Docker Docs Dockerfile Run](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#env)

### ARG 

[Docker Docs Dockerfile Run](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#arg)

### RUN 

[Docker Docs Dockerfile Run](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run)


### EXPOSE

[Docker Docs Dockerfile Run](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#expose)

